<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="192.168.1.5" ignored="0" name="Test" tests="6" failures="6" timestamp="22 Sep 2019 15:07:04 GMT" time="0.05" errors="0">
  <testcase name="testApp1" time="0.011" classname="test.api_tests.BerryTests">
    <failure type="java.lang.AssertionError" message="a expected:&amp;lt;a&amp;gt; but was:&amp;lt;Validation for value of key answer Failed&amp;gt;">
      <![CDATA[java.lang.AssertionError: a expected:<a> but was:<Validation for value of key answer Failed>at test.api_tests.BerryTests.testApp1(BerryTests.java:18)... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- testApp1 -->
  <testcase name="testApp2" time="0.001" classname="test.api_tests.BerryTests">
    <failure type="java.lang.AssertionError" message="a expected:&amp;lt;a&amp;gt; but was:&amp;lt;Validation for value of key answer Failed&amp;gt;">
      <![CDATA[java.lang.AssertionError: a expected:<a> but was:<Validation for value of key answer Failed>at test.api_tests.BerryTests.testApp2(BerryTests.java:23)... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- testApp2 -->
  <testcase name="testApp3" time="0.001" classname="test.api_tests.BerryTests">
    <failure type="java.lang.AssertionError" message="a expected:&amp;lt;a&amp;gt; but was:&amp;lt;Validation for value of key answer Failed&amp;gt;">
      <![CDATA[java.lang.AssertionError: a expected:<a> but was:<Validation for value of key answer Failed>at test.api_tests.BerryTests.testApp3(BerryTests.java:28)... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- testApp3 -->
  <testcase name="testApp1" time="0.0" classname="test.api_tests.j">
    <failure type="java.lang.AssertionError" message="a expected:&amp;lt;a&amp;gt; but was:&amp;lt;Validation for value of key answer Failed&amp;gt;">
      <![CDATA[java.lang.AssertionError: a expected:<a> but was:<Validation for value of key answer Failed>at test.api_tests.j.testApp1(j.java:12)... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- testApp1 -->
  <testcase name="testApp2" time="0.001" classname="test.api_tests.j">
    <failure type="java.lang.AssertionError" message="a expected:&amp;lt;a&amp;gt; but was:&amp;lt;Validation for value of key answer Failed&amp;gt;">
      <![CDATA[java.lang.AssertionError: a expected:<a> but was:<Validation for value of key answer Failed>at test.api_tests.j.testApp2(j.java:17)... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- testApp2 -->
  <testcase name="testApp3" time="0.001" classname="test.api_tests.j">
    <failure type="java.lang.AssertionError" message="a expected:&amp;lt;a&amp;gt; but was:&amp;lt;Validation for value of key answer Failed&amp;gt;">
      <![CDATA[java.lang.AssertionError: a expected:<a> but was:<Validation for value of key answer Failed>at test.api_tests.j.testApp3(j.java:22)... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- testApp3 -->
</testsuite> <!-- Test -->
